### PR TITLE
OCPCLOUD-2182: Update to match K8s v1.28 dependencies

### PR DESCRIPTION
**Pull request by yanhua121**
**What this PR does / why we need it**:
Update dependencies versions to match K8s v1.28.

**How Has This Been Tested?**:
Manual tested.

_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and test output_
Tested with a local Nutanix OCP cluster with the nightly build 4.15.0-0.nightly-2023-09-29-095642. Built the nutanix-ccm container image locally and replace the nutanix-ccm pods image with this one in the cluster. Tested the expected CCM functionalities and it worked fine.

2. If no release note is required, just write "NONE".
None

The upstream PR is https://github.com/nutanix-cloud-native/cloud-provider-nutanix/pull/114.

### CODE REVIEW

**Comment by elmiko** [comment]
linking to jira card for this

/retitle OCPCLOUD-2182: Update to match K8s v1.28 dependencies

**Comment by elmiko** [comment]
thanks @yanhua121 , otherwise the update here looks good to me

**Comment by yanhua121** [comment]
> thanks @yanhua121 , otherwise the update here looks good to me

@elmiko I can reproduce the statefulset issue with the nutanix-csi installed in a local OCP 4.15 cluster. The cluster is using the 4.15 nightly build packet. I suspect the issue is related to nutanix-csi driver/provisioner. I am reporting this issue to our nutanix-csi team. So it means that the e2e-nutanix statefulset failures are not caused by this PR.

**Comment by elmiko** [comment]
thanks @yanhua121 , i think it's ok for us to merge this since the issue appears to be on the storage side.

/approve
/lgtm

**Comment by yanhua121** [comment]
> /retest-required
> Remaining retests: 0 against base HEAD and 2 for PR HEAD  in total

@elmiko Can we skip retesting "e2e-nutanix" for the PR to merge?

**Pull request merged**
