### PR TITLE
NO-JIRA: Add .ci-operator.yaml file

### PR DESCRIPTION
**Pull request by racheljpg**
This is a PR to add a .ci-operator.yaml file to run jobs from the included image. Thanks!

### CODE REVIEW

**Review by damdo — COMMENTED** [review]
/lgtm

**Comment by JoelSpeed** [comment]
This is creating [image building failures](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cloud-provider-nutanix/24/pull-ci-openshift-cloud-provider-nutanix-main-e2e-nutanix/1731651381078528000/artifacts/e2e-nutanix/gather-extra/artifacts/pods/openshift-machine-api_machine-api-controllers-6c88696b57-8x4vg_machine-controller.log), do these image failures exist in master? Are we using the correct image?

/approve cancel
/lgtm cancel

**Comment by nrb** [comment]
Compare previous log to [this one](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-release-master-nightly-4.15-e2e-nutanix-ovn/1729834880541396992/artifacts/e2e-nutanix-ovn/gather-extra/artifacts/pods/openshift-machine-api_machine-api-controllers-54684dcd85-v82lq_machine-controller.log)

**Comment by JoelSpeed** [comment]
/approve
/lgtm

The CCM was working on this older commit, but the MAPI provider was not. The MAPI provider has already updated to RHEL9 and that has broken the CI builds, we need to merge this in order to move on

**Comment by JoelSpeed** [comment]
/override ci/prow/e2e-nutanix
/override ci/prow/e2e-nutanix-window

Can see the CCM is working correctly, Machine API provider is known to be broken, this is blocking the fix for that

**Pull request merged**
